# 3.2 Practica. Análisis, implementación y prueba de una máquina de aprendizaje supervisado (Parte II).

## Introducción de la actividad.

Dada una base de datos 𝐷={𝑡1,𝑡2,…,𝑡𝑛} de tuplas o registros (individuos) y un conjunto de clases 𝐶={𝐶1,𝐶2,…,𝐶𝑚}, el problema de la clasificación es encontrar una función 𝑓:𝐷→𝐶 tal que cada 𝑡𝑖 es asignada una clase 𝐶𝑗. 𝑓:𝐷→𝐶 podría ser Random Forest, una Red Neuronal, una Máquina de Soporte Vectorial, etc.

El análisis, implementación y prueba de una máquina de aprendizaje supervisado (Parte II: Random Forest, una Red Neuronal, una Máquina de Soporte Vectorial), permitirá comprender el funcionamiento de forma clara y precisa.

## Propósito de la actividad

Comprender el funcionamiento de las máquinas de aprendizaje supervisado (Parte II: Random Forest, una Red Neuronal, una Máquina de Soporte Vectorial).

## Instrucciones.

Analicé, implemente y pruebe una máquina de aprendizaje supervisado(Parte II: Random Forest, una Red Neuronal, una Máquina de Soporte Vectorial), la implementación de la máquina será en el lenguaje de su preferencia. La práctica deberá ser presentada en un archivo PDF, que deberá contener:

- Portada
- Análisis de la máquina de aprendizaje supervisado (funcionamiento del algoritmo).
- Implementación de la máquina de aprendizaje supervisado (implementación del algoritmo).
- Prueba de la máquina de aprendizaje supervisado (prueba del algoritmo).
- Conclusiones.

## Análisis de la Red Neuronal

### ¿Qué es una Red Neuronal Artificial?

Una Red Neuronal Artificial es un modelo inspirado en el funcionamiento del cerebro humano, compuesto por neuronas artificiales organizadas en capas:

- Capa de entrada
- Capas ocultas
- Capa de salida
- Cada neurona realiza una combinación lineal de las entradas, seguida de una función de activación.

### Funcionamiento general

1. Los datos de entrada se propagan hacia adelante (*forward propagation*) a través de la red neuronal.
2. Cada neurona realiza un cálculo lineal de sus entradas, definido como:

$$
z = \sum_{i=1}^{n} w_i x_i + b
$$

donde:
- \(x_i\) son las entradas
- \(w_i\) son los pesos
- \(b\) es el sesgo (*bias*)

3. Al resultado \(z\) se le aplica una **función de activación**, como ReLU, para introducir no linealidad en el modelo.
4. El error de la predicción se calcula mediante una **función de pérdida**, que mide la diferencia entre la salida real y la salida esperada.
5. Los pesos y sesgos de la red se ajustan utilizando el algoritmo de **retropropagación (*backpropagation*)**.
6. Este proceso se repite de forma iterativa hasta minimizar el error del modelo.

### Ventajas

- Capacidad para modelar relaciones complejas y no lineales
- Buen desempeño en problemas de clasificación
- Escalables a grandes volúmenes de datos

### Desventajas

- Mayor costo computacional
- Requiere ajuste de hiperparámetros
- Menor interpretabilidad que modelos simples

## Conjunto de datos

Se utilizará un conjunto de datos sencillo relacionado con clientes de una tienda para predecir si compran o no un producto según:

- Edad

- Ingreso mensual

Clases:

- 0 → No compra

- 1 → Sí compra

## Implementación de la Red Neuronal (Python)

### Importación de librerías

In [12]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Creación del dataset

In [13]:
data = {
    "Edad": [
        18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
        38, 40, 42, 44, 46, 48, 50, 52, 54, 56,
        21, 23, 25, 27, 29, 31, 33, 35, 37, 39,
        41, 43, 45, 47, 49, 51, 53, 55, 57, 59,
        27, 34, 41, 48, 55, 29, 36, 43, 50, 58
    ],
    "Ingreso": [
        8000, 9000, 11000, 13000, 15000, 17000, 19000, 21000, 23000, 25000,
        27000, 30000, 33000, 36000, 39000, 42000, 45000, 48000, 51000, 54000,
        10000, 12000, 14000, 16000, 18000, 20000, 22000, 24000, 26000, 28000,
        32000, 35000, 38000, 41000, 44000, 47000, 50000, 53000, 56000, 59000,
        16500, 25500, 34500, 43500, 52500, 18500, 27500, 36500, 45500, 57500
    ],
    "Compra": [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 0, 0, 1, 1, 1
    ]
}

df = pd.DataFrame(data)
df

Edad  Ingreso  Compra
0     18     8000       0
1     20     9000       0
2     22    11000       0
3     24    13000       0
4     26    15000       0
5     28    17000       0
6     30    19000       0
7     32    21000       0
8     34    23000       0
9     36    25000       0
10    38    27000       0
11    40    30000       1
12    42    33000       1
13    44    36000       1
14    46    39000       1
15    48    42000       1
16    50    45000       1
17    52    48000       1
18    54    51000       1
19    56    54000       1
20    21    10000       0
21    23    12000       0
22    25    14000       0
23    27    16000       0
24    29    18000       0
25    31    20000       0
26    33    22000       0
27    35    24000       0
28    37    26000       0
29    39    28000       0
30    41    32000       1
31    43    35000       1
32    45    38000       1
33    47    41000       1
34    49    44000       1
35    51    47000       1
36    53    50000       1
37    55    53000       1
38    57    56000       1
39    59    59000       1
40    27    16500       0
41    34    25500       0
42    41    34500       1
43    48    43500       1
44    55    52500       1
45    29    18500       0
46    36    27500       0
47    43    36500       1
48    50    45500       1
49    58    57500       1

### Separación de variables

In [14]:
X = df[["Edad", "Ingreso"]]
y = df["Compra"]

### División en entrenamiento y prueba

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

### Escalado de datos

Obligatorio en redes neuronales

In [16]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Creación y entrenamiento de la red neuronal

In [17]:
mlp = MLPClassifier(
    hidden_layer_sizes=(8, 4),
    activation="relu",
    solver="adam",
    max_iter=1000,
    random_state=42
)

mlp.fit(X_train, y_train)


c:\Users\sebas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(8, 4), max_iter=1000, random_state=42)

## Prueba del modelo

### Predicciones

In [18]:
y_pred = mlp.predict(X_test)
y_pred

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0])

### Exactitud

In [19]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

### Matriz de confusion

In [20]:
confusion_matrix(y_test, y_pred)

array([[6, 0],
       [0, 9]])

### Reporte de clasificación

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



### Clasificación de un nuevo cliente

In [22]:
nuevo_cliente = pd.DataFrame(
    [[35, 30000]],
    columns=["Edad", "Ingreso"]
)

nuevo_cliente = scaler.transform(nuevo_cliente)
prediction = mlp.predict(nuevo_cliente)

prediction

array([0])

El modelo predice que el nuevo cliente **no realizará la compra** (clase 0),
considerando su edad y nivel de ingreso en comparación con los clientes
más cercanos del conjunto de entrenamiento.

## Conclusiones

- Las Redes Neuronales Artificiales son modelos potentes para clasificación supervisada.
- Permiten capturar relaciones no lineales entre las variables.
- El escalado de datos es indispensable para un correcto funcionamiento.
- Aunque requieren mayor ajuste que KNN, ofrecen mayor flexibilidad.
- Son ampliamente utilizadas en aplicaciones reales de inteligencia artificial.

## Referencias

[Repositorio de GitHub con Jupiter Notebook de la Practica.](https://github.com/RKCbas/Maestria-en-Inteligencia-Artificial---Practicas/blob/main/Cuatrimestre%201/2%20-%20Inteligencia%20artificial%20en%20la%20transformacion%20digital/Practica%203.2.ipynb)